# Actividad

La idea de esta actividad es que te familiarices con el flujo de trabajo necesario para entrenar y predecir con una red neuronal. Para esto debes hacer un clasificador de números del _dataset_ MNIST. La idea hacer un clasificador que diga que dígito está viendo. La idea es que el clasificador lo construyas con una red neuronal. En concreto se pide:

### Parte 1 (4.5 pts)

- Divide el _dataset_ MNIST en 70% de entrenamiento y 30% de prueba.
- Entrena un modelo de Red Neuronal (puede ser MLP o CNN).
- Prueba con varias configuraciones (ej. cambia la función de activación, el número de capas, el número de neuronas, etc) y detalla cuál crees que es la mejor forma de instanciar la red, analizando la matriz de confusión sobre los datos de prueba. Además describe en detalle todo el proceso de escoger los hiperparámetros.

### Parte 2 (1.5 pts)

Hay redes convolucionales que logran hasta 99% de accuracy sobre el _dataset_ MNIST. Averigua por tu cuenta qué configuración usa y descríbela.

### Bonus (1 pto)

Si escoges hacer la parte 1 con una **red convolucional** que logra un _accuracy_ destacable puedes tener nota máxima 8.

## Detalles Académicos

La actividad pueden realizarla en grupos de hasta dos personas. La entrega de esta actividad debe ser un archivo comprimido donde se encuentre un Jupyter Notebook con tu solución, junto a cualquier archivo que estés llamando desde tu código. La fecha de entrega es hasta el viernes 11 de diciembre hasta las 22:00 pm, cualquier entrega después de este plazo no será considerada. El archivo comprimido se entrega en el cuestionario correspondiente de Webcursos.

#Desarrollo
Nuestro primera forma de desarrollar esta actividad es utilizando MLP. Luego de eso utilizamos train_test_split para generar el 70% de entrenamiento y 30% de prueba. A su vez utilizaremos multipples modelos con Relu, relu6 y swish para ver cual de ellas nos entrega el mejor accuracy.
# 1° Dos Layers, 128 neuronas cada uno, con 3 epocas - Relu

In [2]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
import numpy as np
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x = np.concatenate((x_train, x_test))
y = np.concatenate((y_train, y_test))
#data de 0,7 entrenamiento y 0,3 de test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

#ESTO NO ES NECESARIO, PERO SIRVE PARA TENER UN MEJOR RESULTADO
x_train = tf.keras.utils.normalize(x_train, axis=1)
x_test = tf.keras.utils.normalize(x_test, axis=1)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

model.compile(optimizer= 'adam',loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(x_train,y_train,epochs=3)

print("Resultados del modelo")
val_loss, val_acc = model.evaluate(x_test,y_test)
print('perdida:',round(val_loss,4),'accuracy', round(val_acc,4))
from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
arreglo=[]
for punto in y_pred:
  arreglo.append(np.argmax(punto))

y_pred=np.array(arreglo)
confusion_matrix(y_test, y_pred)

11493376/11490434 [==============================] - 0s 0us/step
Epoch 1/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.2880 - accuracy: 0.9162
Epoch 2/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.1182 - accuracy: 0.9643
Epoch 3/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0793 - accuracy: 0.9752
Resultados del modelo
657/657 [==============================] - 1s 2ms/step - loss: 0.0932 - accuracy: 0.9710
perdida: 0.0932 accuracy 0.971


array([[2001,    1,    2,    0,    1,    4,    5,    2,    8,    0],
       [   0, 2272,    6,    3,    2,    0,    0,    3,    8,    0],
       [   2,    6, 2119,    5,   12,    0,    2,    5,    9,    0],
       [   2,   10,   23, 2013,    0,   23,    1,   19,   24,    4],
       [   1,    5,    8,    0, 1964,    1,    8,    2,    6,   22],
       [   5,    4,    3,   25,    2, 1829,   19,    3,   16,    5],
       [  10,    8,    1,    0,    4,    7, 2109,    0,    7,    0],
       [   4,    9,   26,    3,    4,    1,    0, 2210,    1,    7],
       [   4,   13,    8,   16,    6,    5,    3,    3, 1942,    4],
       [   9,    5,    0,   24,   35,    6,    0,   16,   32, 1933]])

#2° Dos Layers, 128 neuronas cada uno, con 3 epocas - Relu6

In [86]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu6))
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu6))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

model.compile(optimizer= 'adam',loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(x_train,y_train,epochs=3)
print("Resultados del modelo","/n")
val_loss, val_acc = model.evaluate(x_test,y_test)
print('perdida:',round(val_loss,6),'accuracy',round(val_acc,6))
from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
arreglo=[]
for punto in y_pred:
  arreglo.append(np.argmax(punto))

y_pred=np.array(arreglo)
confusion_matrix(y_test, y_pred)

Epoch 1/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.2883 - accuracy: 0.9166
Epoch 2/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.1186 - accuracy: 0.9632
Epoch 3/3
657/657 [==============================] - 1s 1ms/step - loss: 0.1262 - accuracy: 0.9619
perdida: 0.126161 accuracy 0.961905


array([[2052,    3,   47,    3,    4,   12,   10,    3,    3,    3],
       [   0, 2322,    8,    1,    0,    1,    1,    3,    0,    1],
       [   1,   11, 2055,    6,    3,    1,    3,   10,    1,    0],
       [   0,   18,   46, 1994,    1,   19,    1,   22,   13,    5],
       [   1,   16,    8,    0, 2000,    1,    4,    8,    2,    8],
       [   1,    5,    2,   16,    2, 1801,   10,    8,   14,    6],
       [   7,   12,    3,    0,    5,   20, 1988,    0,    4,    0],
       [   0,   11,   16,    0,    6,    1,    0, 2148,    0,    3],
       [   2,   64,   38,   20,   13,   15,    2,   15, 1856,    7],
       [   4,    6,    6,   11,   48,   17,    0,   55,   13, 1984]])

#3° Dos Layers, 128 neuronas cada uno, con 3 epocas - Swish

In [90]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation = tf.nn.swish))
model.add(tf.keras.layers.Dense(128, activation = tf.nn.swish))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

model.compile(optimizer= 'adam',loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(x_train,y_train,epochs=3)
print("Resultados del modelo","/n")
val_loss, val_acc = model.evaluate(x_test,y_test)
print('perdida:',round(val_loss,6),'accuracy',round(val_acc,6))
from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
arreglo=[]
for punto in y_pred:
  arreglo.append(np.argmax(punto))

y_pred=np.array(arreglo)
confusion_matrix(y_test, y_pred)

Epoch 1/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.3190 - accuracy: 0.9055
Epoch 2/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.1389 - accuracy: 0.9567
Epoch 3/3
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0938 - accuracy: 0.9701
Resultados del modelo /n
657/657 [==============================] - 1s 1ms/step - loss: 0.1083 - accuracy: 0.9666
perdida: 0.108288 accuracy 0.966619


array([[2105,    0,    6,    0,    1,    5,   18,    0,    4,    1],
       [   0, 2301,    4,    5,    2,    2,   10,    6,    2,    5],
       [  10,    4, 2042,   13,    4,    4,    2,    6,    4,    2],
       [   2,    7,   25, 1993,    1,   64,    1,   11,   11,    4],
       [   2,    7,   11,    0, 2007,    0,    4,    3,    2,   12],
       [   6,    0,    2,   13,    2, 1794,   34,    0,   10,    4],
       [  11,    1,    5,    0,   12,    4, 2002,    0,    4,    0],
       [   2,    8,   13,    2,    3,    2,    0, 2149,    2,    4],
       [   8,   21,   17,   13,   11,   13,   24,   10, 1903,   12],
       [   8,    2,    2,   18,   45,   19,    0,   32,   15, 2003]])

Viendo los resultados obtenidos podemos notar como Relu es la función de activación que nos entrega el mejor resultado, por lo mismo lo utilizaremos para cuando modifiquemos las epocas y la cantidad de neuronas.
# 1° Dos Layers, 128 neuronas cada uno, con 8 epocas

In [87]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

model.compile(optimizer= 'adam',loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(x_train,y_train,epochs=8)

print("Resultados del modelo")
val_loss, val_acc = model.evaluate(x_test,y_test)
print('perdida:',round(val_loss,6),'accuracy',round(val_acc,6))
from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
arreglo=[]
for punto in y_pred:
  arreglo.append(np.argmax(punto))

y_pred=np.array(arreglo)
confusion_matrix(y_test, y_pred)

Epoch 1/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.2909 - accuracy: 0.9169
Epoch 2/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.1211 - accuracy: 0.9633
Epoch 3/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0832 - accuracy: 0.9739
Epoch 4/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0612 - accuracy: 0.9798
Epoch 5/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0468 - accuracy: 0.9845
Epoch 6/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0339 - accuracy: 0.9889
Epoch 7/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0295 - accuracy: 0.9903
Epoch 8/8
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0233 - accuracy: 0.9921
Resultados del modelo
657/657 [==============================] - 1s 1ms/step - loss: 0.1004 - accuracy: 0.9722
perdida: 0.100431 accuracy 0.972238


array([[2115,    2,    7,    0,    0,    3,    2,    1,    9,    1],
       [   0, 2304,    6,    4,    1,    2,    1,    4,   13,    2],
       [   5,    6, 2028,   11,    2,    2,    2,   13,   21,    1],
       [   1,    6,   18, 2024,    0,   21,    0,    9,   29,   11],
       [   0,    4,    9,    0, 1959,    4,    5,    5,    7,   55],
       [   7,    0,    0,   16,    0, 1788,    8,    5,   31,   10],
       [   8,    2,    2,    0,    5,    9, 1996,    0,   17,    0],
       [   2,    6,   15,    3,    4,    2,    0, 2125,    3,   25],
       [   4,   11,    6,    4,    5,    7,    2,    2, 1983,    8],
       [   6,    2,    2,    3,    4,    8,    0,    8,   16, 2095]])

#2° Dos Layers, 128 neuronas cada uno, con 16 epocas

In [88]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

model.compile(optimizer= 'adam',loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(x_train,y_train,epochs=16)

print("Resultados del modelo")
val_loss, val_acc = model.evaluate(x_test,y_test)
print('perdida:',round(val_loss,6),'accuracy',round(val_acc,6))
from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
arreglo=[]
for punto in y_pred:
  arreglo.append(np.argmax(punto))

y_pred=np.array(arreglo)
confusion_matrix(y_test, y_pred)

Epoch 1/16
1532/1532 [==============================] - 3s 2ms/step - loss: 0.2880 - accuracy: 0.9165
Epoch 2/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.1186 - accuracy: 0.9631
Epoch 3/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.0821 - accuracy: 0.9739
Epoch 4/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.0589 - accuracy: 0.9812
Epoch 5/16
1532/1532 [==============================] - 3s 2ms/step - loss: 0.0445 - accuracy: 0.9853
Epoch 6/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.0347 - accuracy: 0.9882
Epoch 7/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.0263 - accuracy: 0.9910
Epoch 8/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.0226 - accuracy: 0.9930
Epoch 9/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.0180 - accuracy: 0.9936
Epoch 10/16
1532/1532 [==============================] - 4s 2ms/step - loss: 0.017

array([[2112,    1,    7,    0,    0,    1,    5,    4,    7,    3],
       [   0, 2307,    7,    3,    1,    0,    1,    4,   13,    1],
       [   9,    3, 2039,   11,    3,    1,    4,   11,   10,    0],
       [   2,   10,   19, 2036,    1,   17,    0,    5,   24,    5],
       [   2,    1,    6,    1, 1985,    0,   17,   12,    7,   17],
       [   4,    3,    4,   24,    2, 1772,   23,    5,   25,    3],
       [   6,    2,    0,    0,    2,    3, 2018,    1,    7,    0],
       [   1,    5,   26,    7,    5,    2,    0, 2117,   18,    4],
       [   8,   11,    7,   15,    2,    4,    5,    2, 1976,    2],
       [   5,    7,    1,    2,    5,   11,    0,   30,   35, 2048]])

#3° Dos Layers, 512 la primera, 64 la segunda, con 30 epocas

In [91]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(512, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(64, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

model.compile(optimizer= 'adam',loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(x_train,y_train,epochs=30)

print("Resultados del modelo","/n")
val_loss, val_acc = model.evaluate(x_test,y_test)
print('perdida:',round(val_loss,4),'accuracy',round(val_acc,4))

from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
arreglo=[]
for punto in y_pred:
  arreglo.append(np.argmax(punto))

y_pred=np.array(arreglo)
confusion_matrix(y_test, y_pred)

Epoch 1/30
1532/1532 [==============================] - 6s 4ms/step - loss: 0.2408 - accuracy: 0.9285
Epoch 2/30
1532/1532 [==============================] - 6s 4ms/step - loss: 0.0927 - accuracy: 0.9708
Epoch 3/30
1532/1532 [==============================] - 6s 4ms/step - loss: 0.0587 - accuracy: 0.9813
Epoch 4/30
1532/1532 [==============================] - 7s 4ms/step - loss: 0.0411 - accuracy: 0.9863
Epoch 5/30
1532/1532 [==============================] - 6s 4ms/step - loss: 0.0295 - accuracy: 0.9904
Epoch 6/30
1532/1532 [==============================] - 6s 4ms/step - loss: 0.0221 - accuracy: 0.9928
Epoch 7/30
1532/1532 [==============================] - 7s 4ms/step - loss: 0.0199 - accuracy: 0.9933
Epoch 8/30
1532/1532 [==============================] - 8s 5ms/step - loss: 0.0146 - accuracy: 0.9950
Epoch 9/30
1532/1532 [==============================] - 7s 5ms/step - loss: 0.0140 - accuracy: 0.9951
Epoch 10/30
1532/1532 [==============================] - 7s 5ms/step - loss: 0.009

array([[2117,    2,    2,    2,    0,    4,    6,    1,    4,    2],
       [   0, 2310,    6,    4,    1,    2,    3,    2,    7,    2],
       [  11,   15, 2028,    5,    2,    8,    6,   10,    5,    1],
       [   1,    4,   23, 2040,    0,   32,    0,    4,   12,    3],
       [   0,    4,    4,    0, 2002,    2,    8,    5,    4,   19],
       [   1,    1,    0,    6,    1, 1831,   14,    1,    8,    2],
       [   9,    0,    1,    0,    2,    6, 2017,    0,    4,    0],
       [   2,    6,   10,    8,    2,    3,    0, 2144,    2,    8],
       [   4,   12,   11,   10,    7,   11,    9,    3, 1962,    3],
       [   6,    2,    0,    2,    8,   26,    0,   11,    5, 2084]])

Como podemos notar, El resultado maximo que nos entrega la función Relu, incluso modificando las epocas y la cantidad de neuronas a una recomendada nos da 0,9779. Con esto claro pasaremos a utilizar una red neuronal convolucional para ver los resultados que arroja y ver si podemos acercarnos al 0,99.
#1° Convolucional. Dos layers de Relu y una final de softmax
Antes de entregarle los datos debemos cambiar los datos para que se puedan utilizar en CNN.


In [9]:
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D

train_x = x_train.reshape(-1, 28, 28, 1)
test_x = x_test.reshape(-1, 28, 28, 1)
train_y=y_train
modeloCNN = tf.keras.models.Sequential()
modeloCNN.add(Conv2D(150, (3, 3), input_shape=train_x.shape[1:]))
modeloCNN.add(Activation('relu'))
modeloCNN.add(MaxPooling2D(pool_size=(2, 2)))
modeloCNN.add(Conv2D(75, (3, 3)))
modeloCNN.add(Activation('relu'))
modeloCNN.add(MaxPooling2D(pool_size=(2, 2)))
modeloCNN.add(Flatten())
modeloCNN.add(Dense(64))
modeloCNN.add(Activation('softmax'))

modeloCNN.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
modeloCNN.fit(train_x, train_y, epochs = 8)


modeloCNN.summary()

Epoch 1/8
1532/1532 [==============================] - 5s 4ms/step - loss: 0.2346 - accuracy: 0.9284
Epoch 2/8
1532/1532 [==============================] - 5s 3ms/step - loss: 0.0713 - accuracy: 0.9779
Epoch 3/8
1532/1532 [==============================] - 5s 3ms/step - loss: 0.0491 - accuracy: 0.9851
Epoch 4/8
1532/1532 [==============================] - 5s 3ms/step - loss: 0.0362 - accuracy: 0.9887
Epoch 5/8
1532/1532 [==============================] - 5s 4ms/step - loss: 0.0285 - accuracy: 0.9906
Epoch 6/8
1532/1532 [==============================] - 5s 3ms/step - loss: 0.0203 - accuracy: 0.9933
Epoch 7/8
1532/1532 [==============================] - 5s 3ms/step - loss: 0.0166 - accuracy: 0.9945
Epoch 8/8
1532/1532 [==============================] - 5s 3ms/step - loss: 0.0114 - accuracy: 0.9965
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26

In [10]:
print("Resultados del modelo","/n")
val_loss, val_acc = modeloCNN.evaluate(test_x,y_test)
print('perdida:',round(val_loss,4),'accuracy',round(val_acc,4))

Resultados del modelo /n
657/657 [==============================] - 2s 2ms/step - loss: 0.0369 - accuracy: 0.9906
perdida: 0.0369 accuracy 0.9906


Con esto podemos notar como la Red convolucional es mucho más efectiva con los parametros que utilizamos. A su vez podemos ver que a medida que aumentan las epocas de ejecución el accuracy se acercará más y más a uno, por lo que esta red neuronal es mucho más precisa que la MLP.